//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisReg.Cmn.Namings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NamingStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NamingStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisReg.Cmn.Namings.NamingStrings", typeof(NamingStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ακύρωση.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δημιουργία Χρήστη.
        /// </summary>
        public static string BtnCreateUser {
            get {
                return ResourceManager.GetString("BtnCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Καταχώριση Νέας Επίσκεψης.
        /// </summary>
        public static string BtnCreateVisit {
            get {
                return ResourceManager.GetString("BtnCreateVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Καταχώριση Νέου Επισκέπτη.
        /// </summary>
        public static string BtnCreateVisitor {
            get {
                return ResourceManager.GetString("BtnCreateVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διαγραφή.
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επεξεργασία.
        /// </summary>
        public static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λίστα Επισκεπτών.
        /// </summary>
        public static string BtnGetVisitors {
            get {
                return ResourceManager.GetString("BtnGetVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λίστα Χρηστών.
        /// </summary>
        public static string BtnListUser {
            get {
                return ResourceManager.GetString("BtnListUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ΕΙΣΟΔΟΣ.
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εκτύπωση.
        /// </summary>
        public static string BtnReport {
            get {
                return ResourceManager.GetString("BtnReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αποθήκευση.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επίσκεψη.
        /// </summary>
        public static string BtnVisit {
            get {
                return ResourceManager.GetString("BtnVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μητρώο Επισκεπτών K.Y..
        /// </summary>
        public static string TitleAppShortName {
            get {
                return ResourceManager.GetString("TitleAppShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υπουργείο Παιδείας &amp; Θρησκευμάτων.
        /// </summary>
        public static string TitleMinistryName {
            get {
                return ResourceManager.GetString("TitleMinistryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υ.ΠΑΙ.Θ..
        /// </summary>
        public static string TitleMinistryNameShortName {
            get {
                return ResourceManager.GetString("TitleMinistryNameShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τμήμα Υποστηρικτικών Εφαρμογών.
        /// </summary>
        public static string TitleΙΤDepartmentName {
            get {
                return ResourceManager.GetString("TitleΙΤDepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Διεύθυνση Ανάπτυξης Πληροφοριακών Συστημάτων.
        /// </summary>
        public static string TitleΙΤDivisionName {
            get {
                return ResourceManager.GetString("TitleΙΤDivisionName", resourceCulture);
            }
        }
    }
}
