//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisReg.Cmn.Namings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NamingErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NamingErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisReg.Cmn.Namings.NamingErrors", typeof(NamingErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η &apos;&apos;Ωρα Εξόδου&apos; δεν μπορεί να είναι μικρότερη από την &apos;&apos;Ωρα Εισόδου&apos;..
        /// </summary>
        public static string ErrorForTimeExit {
            get {
                return ResourceManager.GetString("ErrorForTimeExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μόνο αριθμητικά ψηφία επιτρέπονται..
        /// </summary>
        public static string OnlyDigits {
            get {
                return ResourceManager.GetString("OnlyDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μόνο κεφαλαίοι αλφαριθμητικοί χαρακτήρες επιτρέπονται..
        /// </summary>
        public static string OnlyUpperAlphabets {
            get {
                return ResourceManager.GetString("OnlyUpperAlphabets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το &apos;Φύλλο&apos; είναι υποχρεωτικό..
        /// </summary>
        public static string SexNameRequired {
            get {
                return ResourceManager.GetString("SexNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το &apos;Email Χρήστη&apos; είναι υποχρεωτικό..
        /// </summary>
        public static string UserEmailRequired {
            get {
                return ResourceManager.GetString("UserEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το &apos;Όνομα Χρήστη&apos; είναι υποχρεωτικό..
        /// </summary>
        public static string UserFirstNameRequired {
            get {
                return ResourceManager.GetString("UserFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η ΄Ομάδα Χρήστη΄ είναι υποχρεωτική..
        /// </summary>
        public static string UserGroupRequired {
            get {
                return ResourceManager.GetString("UserGroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το &apos;Επώνυμο Χρήστη&apos; είναι υποχρεωτικό..
        /// </summary>
        public static string UserLastNameRequired {
            get {
                return ResourceManager.GetString("UserLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το &apos;UserName&apos; είναι υποχρεωτικό..
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η &apos;Επιβεβαίωση Κωδικού&apos; δεν πρέπει να διαφέρει με τον &apos;Κωδικό Πρόσβασης&apos;..
        /// </summary>
        public static string UserPasswordConfirmMismatch {
            get {
                return ResourceManager.GetString("UserPasswordConfirmMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το &apos;Password&apos; είναι υποχρεωτικός..
        /// </summary>
        public static string UserPasswordRequired {
            get {
                return ResourceManager.GetString("UserPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο ΄Χρήστης΄ είναι υποχρεωτικός..
        /// </summary>
        public static string UserRequired {
            get {
                return ResourceManager.GetString("UserRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το &apos;Τηλέφωνο Χρήστη&apos; είναι υποχρεωτικό..
        /// </summary>
        public static string UserTelephoneRequired {
            get {
                return ResourceManager.GetString("UserTelephoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο &apos;Αριθμός Κάρτας&apos; είναι υποχρεωτικός..
        /// </summary>
        public static string VsiCardNumberRequired {
            get {
                return ResourceManager.GetString("VsiCardNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η &apos;Ημ/νία Επίσκεψης&apos; είναι υποχρεωτική..
        /// </summary>
        public static string VsiDateRequired {
            get {
                return ResourceManager.GetString("VsiDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο &apos;Λόγος Επίσκεψης&apos; είναι υποχρεωτικός..
        /// </summary>
        public static string VsiSubjectRequired {
            get {
                return ResourceManager.GetString("VsiSubjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το &apos;Όνομα&apos; είναι υποχρεωτικό..
        /// </summary>
        public static string VstFirstNameRequired {
            get {
                return ResourceManager.GetString("VstFirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο &apos;Αριθμός Ταυτοπρ.&apos; είναι υποχρεωτικός..
        /// </summary>
        public static string VstIdentificationNumberRequired {
            get {
                return ResourceManager.GetString("VstIdentificationNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το &apos;Επώνυμο&apos; είναι υποχρεωτικό..
        /// </summary>
        public static string VstLastNameRequired {
            get {
                return ResourceManager.GetString("VstLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το &apos;Μητρώνυμο&apos; είναι υποχρεωτικό..
        /// </summary>
        public static string VstMotherNameRequired {
            get {
                return ResourceManager.GetString("VstMotherNameRequired", resourceCulture);
            }
        }
    }
}
