//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisReg.Cmn.Namings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NamingViewModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NamingViewModels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisReg.Cmn.Namings.NamingViewModels", typeof(NamingViewModels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ημ/νία Από.
        /// </summary>
        public static string DateVisitFrom {
            get {
                return ResourceManager.GetString("DateVisitFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ημ/νία Έως.
        /// </summary>
        public static string DateVisitTo {
            get {
                return ResourceManager.GetString("DateVisitTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υπάλληλος Επίσκεψης.
        /// </summary>
        public static string EmiFullNameInfo {
            get {
                return ResourceManager.GetString("EmiFullNameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τύπος Ταυτοπρ..
        /// </summary>
        public static string IdcName {
            get {
                return ResourceManager.GetString("IdcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Υπηρεσία Επίσκεψης.
        /// </summary>
        public static string OriName {
            get {
                return ResourceManager.GetString("OriName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Δ/νση Κατοικίας.
        /// </summary>
        public static string ResidenceAddress {
            get {
                return ResourceManager.GetString("ResidenceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τ.Κ..
        /// </summary>
        public static string ResidencePostalCode {
            get {
                return ResourceManager.GetString("ResidencePostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Φύλλο.
        /// </summary>
        public static string SexName {
            get {
                return ResourceManager.GetString("SexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Περιγραφή.
        /// </summary>
        public static string UserDescription {
            get {
                return ResourceManager.GetString("UserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Υπαλλήλου.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όνομα Υπαλλήλου.
        /// </summary>
        public static string UserFirstName {
            get {
                return ResourceManager.GetString("UserFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Περιγραφή Ομάδας.
        /// </summary>
        public static string UserGroupDescription {
            get {
                return ResourceManager.GetString("UserGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ομάδα Χρηστών.
        /// </summary>
        public static string UserGroupName {
            get {
                return ResourceManager.GetString("UserGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address Υπαλλήλου.
        /// </summary>
        public static string UserIPAddress {
            get {
                return ResourceManager.GetString("UserIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ενεργός.
        /// </summary>
        public static string UserIsActive {
            get {
                return ResourceManager.GetString("UserIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επώνυμο Υπαλλήλου.
        /// </summary>
        public static string UserLastName {
            get {
                return ResourceManager.GetString("UserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μετρητής Login.
        /// </summary>
        public static string UserLoginCounter {
            get {
                return ResourceManager.GetString("UserLoginCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ημ/νία Τελ. Login.
        /// </summary>
        public static string UserLoginLastDate {
            get {
                return ResourceManager.GetString("UserLoginLastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τηλέφωνο Υπαλλήλου.
        /// </summary>
        public static string UserTelephone {
            get {
                return ResourceManager.GetString("UserTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Εύρεση Επισκέπτη.
        /// </summary>
        public static string VisitorInfo {
            get {
                return ResourceManager.GetString("VisitorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κατάσταση Επίσκεψης.
        /// </summary>
        public static string VisitStatus {
            get {
                return ResourceManager.GetString("VisitStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κατηγορία Επισκέπτη.
        /// </summary>
        public static string VscName {
            get {
                return ResourceManager.GetString("VscName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Α/Α.
        /// </summary>
        public static string VsiAA {
            get {
                return ResourceManager.GetString("VsiAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αριθμός Κάρτας.
        /// </summary>
        public static string VsiCardNumber {
            get {
                return ResourceManager.GetString("VsiCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σχόλια.
        /// </summary>
        public static string VsiComment {
            get {
                return ResourceManager.GetString("VsiComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ημ/νία Επίσκεψης.
        /// </summary>
        public static string VsiDate {
            get {
                return ResourceManager.GetString("VsiDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ΓΓΑ.
        /// </summary>
        public static string VsiIsForGGA {
            get {
                return ResourceManager.GetString("VsiIsForGGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Συνάντηση.
        /// </summary>
        public static string VsiIsScheduledVisit {
            get {
                return ResourceManager.GetString("VsiIsScheduledVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Γραφείο Επίσκεψης.
        /// </summary>
        public static string VsiOfficeNumber {
            get {
                return ResourceManager.GetString("VsiOfficeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λόγος Επίσκεψης.
        /// </summary>
        public static string VsiSubject {
            get {
                return ResourceManager.GetString("VsiSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ώρα Εισόδου.
        /// </summary>
        public static string VsiTimeEntrance {
            get {
                return ResourceManager.GetString("VsiTimeEntrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ώρα Εξόδου.
        /// </summary>
        public static string VsiTimeExit {
            get {
                return ResourceManager.GetString("VsiTimeExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λόγος Επίσκεψης.
        /// </summary>
        public static string VsrName {
            get {
                return ResourceManager.GetString("VsrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Περιγραφή.
        /// </summary>
        public static string VstDescription {
            get {
                return ResourceManager.GetString("VstDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πατρώνυμο.
        /// </summary>
        public static string VstFatherName {
            get {
                return ResourceManager.GetString("VstFatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Όνομα.
        /// </summary>
        public static string VstFirstName {
            get {
                return ResourceManager.GetString("VstFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ονοματεπώνυμο.
        /// </summary>
        public static string VstFullName {
            get {
                return ResourceManager.GetString("VstFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αριθμός Ταυτοπρ..
        /// </summary>
        public static string VstIdentificationNumber {
            get {
                return ResourceManager.GetString("VstIdentificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Επώνυμο.
        /// </summary>
        public static string VstLastName {
            get {
                return ResourceManager.GetString("VstLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κινητό.
        /// </summary>
        public static string VstMobileNumber {
            get {
                return ResourceManager.GetString("VstMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Μητρώνυμο.
        /// </summary>
        public static string VstMotherName {
            get {
                return ResourceManager.GetString("VstMotherName", resourceCulture);
            }
        }
    }
}
