//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisReg.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeInfo()
        {
            this.VisitInfo = new HashSet<VisitInfo>();
        }
    
        public int EMI_Id { get; set; }
        public Nullable<int> EMI_ORI_Id { get; set; }
        public string EMI_LastName { get; set; }
        public string EMI_FirstName { get; set; }
        public string EMI_Telephone { get; set; }
        public string EMI_Office { get; set; }
        public string EMI_Email { get; set; }
        public string EMI_Attribute { get; set; }
        public bool EMI_IsActive { get; set; }
    
        public virtual OrganizationInfo OrganizationInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitInfo> VisitInfo { get; set; }
    }
}
