//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisReg.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserGroup()
        {
            this.UserUserGroup = new HashSet<UserUserGroup>();
        }
    
        public short USG_Id { get; set; }
        public string USG_PublicCode { get; set; }
        public string USG_Name { get; set; }
        public bool USG_IsAdmin { get; set; }
        public Nullable<short> USG_Order { get; set; }
        public string USG_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserUserGroup> UserUserGroup { get; set; }
    }
}
