//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisReg.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserUserGroup = new HashSet<UserUserGroup>();
            this.VisitInfoLog = new HashSet<VisitInfoLog>();
        }
    
        public short USE_Id { get; set; }
        public string USE_UserName { get; set; }
        public string USE_Salt { get; set; }
        public string USE_Password { get; set; }
        public string USE_FirstName { get; set; }
        public string USE_LastName { get; set; }
        public string USE_Telephone { get; set; }
        public string USE_Email { get; set; }
        public string USE_Description { get; set; }
        public string USE_IPAddress { get; set; }
        public Nullable<System.DateTime> USE_LoginLastDate { get; set; }
        public Nullable<short> USE_LoginCounter { get; set; }
        public bool USE_IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserUserGroup> UserUserGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitInfoLog> VisitInfoLog { get; set; }
    }
}
