//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisReg.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitInfoLog
    {
        public int VIL_Id { get; set; }
        public short VIL_USE_Id { get; set; }
        public short VIL_ACT_Id { get; set; }
        public int VIL_VSI_Id { get; set; }
        public System.DateTime VIL_Date { get; set; }
    
        public virtual ActionType ActionType { get; set; }
        public virtual VisitInfo VisitInfo { get; set; }
        public virtual User User { get; set; }
    }
}
