//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisReg.Dal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VisitInfo()
        {
            this.VisitInfoLog = new HashSet<VisitInfoLog>();
        }
    
        public int VSI_Id { get; set; }
        public int VSI_VST_Id { get; set; }
        public Nullable<short> VSI_VSC_Id { get; set; }
        public System.DateTime VSI_Date { get; set; }
        public string VSI_IdentificationNumber { get; set; }
        public string VSI_CardNumber { get; set; }
        public Nullable<short> VSI_VSR_Id { get; set; }
        public Nullable<int> VSI_EMI_Id { get; set; }
        public Nullable<int> VSI_ORI_Id { get; set; }
        public System.TimeSpan VSI_TimeEntrance { get; set; }
        public Nullable<System.TimeSpan> VSI_TimeExit { get; set; }
        public string VSI_OfficeNumber { get; set; }
        public bool VSI_IsScheduledVisit { get; set; }
        public bool VSI_IsForGGA { get; set; }
        public string VSI_MobileNumber { get; set; }
        public string VSI_Comment { get; set; }
        public bool VSI_IsActive { get; set; }
    
        public virtual EmployeeInfo EmployeeInfo { get; set; }
        public virtual OrganizationInfo OrganizationInfo { get; set; }
        public virtual Visitor Visitor { get; set; }
        public virtual VisitorCategory VisitorCategory { get; set; }
        public virtual VisitReason VisitReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitInfoLog> VisitInfoLog { get; set; }
    }
}
