//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisReg.Dal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VisRegDB : DbContext
    {
        public VisRegDB()
            : base("name=VisRegDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IdentificationCertificate> IdentificationCertificate { get; set; }
        public virtual DbSet<Sex> Sex { get; set; }
        public virtual DbSet<VisitorCategory> VisitorCategory { get; set; }
        public virtual DbSet<UserGroup> UserGroup { get; set; }
        public virtual DbSet<UserUserGroup> UserUserGroup { get; set; }
        public virtual DbSet<EmployeeInfo> EmployeeInfo { get; set; }
        public virtual DbSet<OrganizationInfo> OrganizationInfo { get; set; }
        public virtual DbSet<VisitReason> VisitReason { get; set; }
        public virtual DbSet<Visitor> Visitor { get; set; }
        public virtual DbSet<ActionType> ActionType { get; set; }
        public virtual DbSet<VisitInfo> VisitInfo { get; set; }
        public virtual DbSet<VisitInfoLog> VisitInfoLog { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
